# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 23:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=300, null=True)),
                ('arrival', models.CharField(max_length=300, null=True)),
                ('departure_date', models.DateField(null=True)),
                ('arrival_date', models.DateField(null=True)),
                ('departure_time', models.TimeField(null=True)),
                ('arrival_time', models.TimeField(null=True)),
                ('package_width', models.FloatField(null=True)),
                ('package_height', models.FloatField(null=True)),
                ('package_thickness', models.FloatField(null=True)),
                ('package_weight', models.FloatField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='drivers.Driver')),
            ],
        ),
    ]
