# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('details', models.CharField(max_length=300, null=True)),
                ('departure', models.CharField(max_length=300, null=True)),
                ('arrival', models.CharField(max_length=300, null=True)),
                ('departure_date', models.DateField(null=True)),
                ('arrival_date', models.DateField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
