# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_thickness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_width',
            field=models.FloatField(null=True),
        ),
    ]
