# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20160804_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_weight',
            field=models.FloatField(null=True),
        ),
    ]
