# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_package_package_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
