# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_package_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
