# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0005_package_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
