# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 09:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=300, null=True)),
                ('arrival', models.CharField(max_length=300, null=True)),
                ('departure_date', models.DateField(null=True)),
                ('departure_time', models.TimeField(null=True)),
                ('arrival_date', models.DateField(null=True)),
                ('arrival_time', models.TimeField(null=True)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
